// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'test_utils.dart' as utils_test;
import 'test_item_type.dart' as item_type_test;
import 'test_metadata.dart' as test_metadata;
import 'test_style_type.dart' as test_style_type;

void main() {
  utils_test.main();
  item_type_test.main();
  test_metadata.main();
  test_style_type.main();
  item_type_test.main();
}
