name: contentstack_utils
description: Utils package for Contentstack-dart
version: 1.1.0
homepage: https://www.contentstack.com

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  #dartdoc: ^1.0.2
  lint: ^1.3.0
  path: ^1.7.0
  html: ^0.14.0+4
  logger: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.5
  # test_coverage: ^0.4.1
  