name: contentstack_utils
description: Utils package for Contentstack-dart
version: 1.0.0
homepage: https://www.contentstack.com

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  dartdoc: ^0.45.0
  lint: ^1.3.0
  path: ^1.7.0
  logger: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.17.5
  # test_coverage: ^0.5.0
  