name: contentstack_utils
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://www.contentstack.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  dartdoc: any
  html: ^0.14.0+4
  http:
  lint: ^1.3.0
  path: ^1.7.0
  logger: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  test_coverage: ^0.5.0
  