name: contentstack_utils
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://www.contentstack.com

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  path: ^1.7.0
  http:
  html: ^0.14.0+4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  test_coverage: ^0.4.2

